"""Orthonormal Einstein tensor of the axial track metric, generated by
scripts/derive_axial_track_einstein.py; edit the derivation script instead.

The (n, z) block equals (C_rr/C) times the frame metric plus wall terms; rr and pp
share the product value -K of the (sigma, z) metric; nr and zr are wall terms only.
"""
from __future__ import annotations

import numpy as np

JET_NAMES = ('alpha', 'alpha_s', 'alpha_ss', 'alpha_sz', 'alpha_sr', 'alpha_z', 'alpha_zz', 'alpha_zr', 'alpha_r', 'alpha_rr', 'A', 'A_s', 'A_ss', 'A_sz', 'A_sr', 'A_z', 'A_zz', 'A_zr', 'A_r', 'A_rr', 'beta', 'beta_s', 'beta_ss', 'beta_sz', 'beta_sr', 'beta_z', 'beta_zz', 'beta_zr', 'beta_r', 'beta_rr', 'C', 'C_r', 'C_rr')

def wall_nn(j):
    alpha, alpha_s, alpha_ss, alpha_sz, alpha_sr, alpha_z, alpha_zz, alpha_zr, alpha_r, alpha_rr, A, A_s, A_ss, A_sz, A_sr, A_z, A_zz, A_zr, A_r, A_rr, beta, beta_s, beta_ss, beta_sz, beta_sr, beta_z, beta_zz, beta_zr, beta_r, beta_rr, C, C_r, C_rr = (j[name] for name in JET_NAMES)
    return (-2*A**5*C*alpha**6*beta_r**2 - 8*A**2*A_r*C_r*alpha**8 - 8*A**2*A_rr*C*alpha**8)/(8*A**3*C*alpha**8)

def wall_nz(j):
    alpha, alpha_s, alpha_ss, alpha_sz, alpha_sr, alpha_z, alpha_zz, alpha_zr, alpha_r, alpha_rr, A, A_s, A_ss, A_sz, A_sr, A_z, A_zz, A_zr, A_r, A_rr, beta, beta_s, beta_ss, beta_sz, beta_sr, beta_z, beta_zz, beta_zr, beta_r, beta_rr, C, C_r, C_rr = (j[name] for name in JET_NAMES)
    return (-4*A**3*C*alpha**6*beta_rr + 4*A**3*C*alpha**5*alpha_r*beta_r - 4*A**3*C_r*alpha**6*beta_r - 12*A**2*A_r*C*alpha**6*beta_r)/(8*A**2*C*alpha**7)

def wall_zz(j):
    alpha, alpha_s, alpha_ss, alpha_sz, alpha_sr, alpha_z, alpha_zz, alpha_zr, alpha_r, alpha_rr, A, A_s, A_ss, A_sz, A_sr, A_z, A_zz, A_zr, A_r, A_rr, beta, beta_s, beta_ss, beta_sz, beta_sr, beta_z, beta_zz, beta_zr, beta_r, beta_rr, C, C_r, C_rr = (j[name] for name in JET_NAMES)
    return (-6*A**5*C*alpha**4*beta_r**2 + 8*A**3*C*alpha**5*alpha_rr + 8*A**3*C_r*alpha**5*alpha_r)/(8*A**3*C*alpha**6)

def wall_nr(j):
    alpha, alpha_s, alpha_ss, alpha_sz, alpha_sr, alpha_z, alpha_zz, alpha_zr, alpha_r, alpha_rr, A, A_s, A_ss, A_sz, A_sr, A_z, A_zz, A_zr, A_r, A_rr, beta, beta_s, beta_ss, beta_sz, beta_sr, beta_z, beta_zz, beta_zr, beta_r, beta_rr, C, C_r, C_rr = (j[name] for name in JET_NAMES)
    return (A**2*alpha**4*beta_zr - 2*A**2*alpha**3*alpha_r*beta_z + A**2*alpha**3*alpha_z*beta_r + 2*A*A_r*alpha**4*beta_z + 2*A*A_s*alpha**3*alpha_r - 2*A*A_sr*alpha**4 + A*A_z*alpha**4*beta_r - 2*A*A_z*alpha**3*alpha_r*beta + 2*A*A_zr*alpha**4*beta)/(2*A**2*alpha**5)

def wall_zr(j):
    alpha, alpha_s, alpha_ss, alpha_sz, alpha_sr, alpha_z, alpha_zz, alpha_zr, alpha_r, alpha_rr, A, A_s, A_ss, A_sz, A_sr, A_z, A_zz, A_zr, A_r, A_rr, beta, beta_s, beta_ss, beta_sz, beta_sr, beta_z, beta_zz, beta_zr, beta_r, beta_rr, C, C_r, C_rr = (j[name] for name in JET_NAMES)
    return (A**4*alpha**2*beta*beta_zr + 2*A**4*alpha**2*beta_r*beta_z - A**4*alpha**2*beta_sr + A**4*alpha*alpha_s*beta_r - A**4*alpha*alpha_z*beta*beta_r - 3*A**3*A_s*alpha**2*beta_r + 3*A**3*A_z*alpha**2*beta*beta_r - 2*A**2*alpha**3*alpha_zr + 2*A*A_r*alpha**3*alpha_z)/(2*A**3*alpha**4)

def wall_rr(j):
    alpha, alpha_s, alpha_ss, alpha_sz, alpha_sr, alpha_z, alpha_zz, alpha_zr, alpha_r, alpha_rr, A, A_s, A_ss, A_sz, A_sr, A_z, A_zz, A_zr, A_r, A_rr, beta, beta_s, beta_ss, beta_sz, beta_sr, beta_z, beta_zz, beta_zr, beta_r, beta_rr, C, C_r, C_rr = (j[name] for name in JET_NAMES)
    return (2*A**5*C*alpha**4*beta_r**2 + 8*A**3*C_r*alpha**5*alpha_r + 8*A**2*A_r*C*alpha**5*alpha_r + 8*A**2*A_r*C_r*alpha**6)/(8*A**3*C*alpha**6)

def wall_pp(j):
    alpha, alpha_s, alpha_ss, alpha_sz, alpha_sr, alpha_z, alpha_zz, alpha_zr, alpha_r, alpha_rr, A, A_s, A_ss, A_sz, A_sr, A_z, A_zz, A_zr, A_r, A_rr, beta, beta_s, beta_ss, beta_sz, beta_sr, beta_z, beta_zz, beta_zr, beta_r, beta_rr, C, C_r, C_rr = (j[name] for name in JET_NAMES)
    return (-2*A**5*C*alpha**4*beta_r**2 + 8*A**3*C*alpha**5*alpha_rr + 8*A**2*A_r*C*alpha**5*alpha_r + 8*A**2*A_rr*C*alpha**6)/(8*A**3*C*alpha**6)

def product_rr(j):
    alpha, alpha_s, alpha_ss, alpha_sz, alpha_sr, alpha_z, alpha_zz, alpha_zr, alpha_r, alpha_rr, A, A_s, A_ss, A_sz, A_sr, A_z, A_zz, A_zr, A_r, A_rr, beta, beta_s, beta_ss, beta_sz, beta_sr, beta_z, beta_zz, beta_zr, beta_r, beta_rr, C, C_r, C_rr = (j[name] for name in JET_NAMES)
    return (-8*A**3*C*alpha**4*beta*beta_zz + 8*A**3*C*alpha**4*beta_sz - 8*A**3*C*alpha**4*beta_z**2 - 8*A**3*C*alpha**3*alpha_s*beta_z + 8*A**3*C*alpha**3*alpha_z*beta*beta_z + 16*A**2*A_s*C*alpha**4*beta_z + 8*A**2*A_s*C*alpha**3*alpha_s - 8*A**2*A_s*C*alpha**3*alpha_z*beta - 8*A**2*A_ss*C*alpha**4 + 16*A**2*A_sz*C*alpha**4*beta - 24*A**2*A_z*C*alpha**4*beta*beta_z + 8*A**2*A_z*C*alpha**4*beta_s - 8*A**2*A_z*C*alpha**3*alpha_s*beta + 8*A**2*A_z*C*alpha**3*alpha_z*beta**2 - 8*A**2*A_zz*C*alpha**4*beta**2 + 8*A*C*alpha**5*alpha_zz - 8*A_z*C*alpha**5*alpha_z)/(8*A**3*C*alpha**6)

